### ISSUE TITLE
TODO: List of Games with shader issue.

### ISSUE THREAD

**Issue by Zangetsu38** [Vita3K/Vita3K#1395]
i have thinks open Issue for can trace and set like a not list of game affected with this shader frag or vertex issue.
Like wrong color/texture/black screen.hidden render, etc.. and for vertex shader like vertex explosed and etc

# Gravity rush
- [ ] Wrong color
- [ ] fluo flashing color
- [ ] texture is very darkness
- [ ] vertex body explosed

# One Piece Unlimited WR
- [ ] wrong color on enviroenemt
- [ ] wrong color on body
- [ ] luffy and pnj invisible
- screen flashing: shader issue ?

# Call of duty blackops
- [ ] render hidden by black screen
- [ ] wrong color (all is blue)
- [ ] is very darkness

# WRC 5
- [ ] wrong color  for cars
- [ ] wrong color for decors
- [ ] black box on three
- screen flashing: shader issue ?

# Geometry Wars:
- [ ] wrong/broken texture
- [ ] vertex explosed ingame

# Valkyrie drive:
- [ ] tv crypted effect by one frag shader
- [ ] wrong color or texture in body
- [ ] wrong color or texture on enviroenemt

# To love ru battle ectazy:
- [ ] wrong texture on charachter body inside house

**Comment by Zangetsu38** [comment]
totally forget this issue 💀 

# PT
- [ ] Color issue
- [ ] yellow screen flashing
![image](https://user-images.githubusercontent.com/5261759/141203606-05043198-709a-464a-8511-5437d2abd9af.png)

**Comment by marcoluc97** [comment]
I think u can pin an issue on Github if need a Meta like or tracking list...

**Comment by GamingDucking** [comment]
as of the latest bulid, Flower and Oddworld: Munch's Oddysee HD problems are fixed

**Comment by scribam** [comment]
@Zangetsu38 can you update this issue please?
