### ISSUE TITLE
Shader generation TODO

### ISSUE THREAD

**Issue by pent0** [Vita3K/Vita3K#417]
**Features**:
- [x] Constant (`FPCONSTANT`) operands
- [x] Immediate (`IMMEDIATE`) operands
- [x] Index ('INDEX') operands
- [x] Indexed ('INDEXED') operands (partial)
- Support emitting 
  * [x] Arrays and load/store on them
  * [ ] Structs and load/store on them
- Non-f32 types support
   * [x] Texture queries
   * [x] Instructions operation
   * [x] Parameters
- [x] PHAS (phases)
- [x] Literals

**Fixes**:
- [x] Correct secondary attribute (`SECATTR`) generation 
- [x] Writeable pa index register is supposed to be aligned (e.g: pa0_writeable, pa4_writeable, pa8_writeable)

**Bugs/Crashes**:
- [x] Fix **Flood It** compile error: `error C7011: implicit cast from "vec4" to "vec2"`
~~ [ ] Fix infinite compilation loop when a shader fails to compile (ie. happens on above game)~~ Not a bug

**Optimizations**
- [x] Omit multiplication/division by `vecN(1.0)`

**Comment by sunho** [comment]
- [ ] Int/uint instructions
- [ ] Memory instructions
- [ ] Hi/lo
- [ ] Modifier/mask on many instructions
- [ ] Look into repeat mode
- [ ] Reuse common parse steps
- [ ] More readable shader code generation
- [ ] Instruction parser update script
- [ ] Look into different data types in vertex and fragment
