### ISSUE TITLE
Improve shader disassembler

### ISSUE THREAD

**Issue by sunho** [Vita3K/Vita3K#792]
# About

Our disassembler has some room for improvement. It especially lacks testing.

# TODOs
- [ ] Organize disassembly format
- [ ] Separate disassembler from translator
- [x] Instruction parser update script
- [ ] Modifier/mask on many instructions
- [ ] Common repeat mode parse function
- [ ] Add automatic tests
- [ ] Add missing log_disasm
- [ ] Order the instructions as in the gxp
